### ISSUE TITLE
EVM Integrate Wallet connect in mobile with Wagmi

### ISSUE THREAD

**Issue by MSghais** [AFK-AlignedFamKernel/afk_monorepo#129]
# Description

EVMProviders is already created.
We have an issue when adding it in the app/Wrapper.

- [ ] Fix EVMProviders issues with siwe-auth reown/wallet connect
- [ ] Integration of EVM wallet
- [ ] Screen EVM connect
- [ ] Add in the UI

**Comment by ShantelPeters** [comment]
Hi

**Comment by Ayoazeez26** [comment]
HI @MSghais can I work on this?

**Comment by martinvibes** [comment]
hey @MSghais i would love to work on this :)

**Comment by NueloSE** [comment]
@MSghais can i work on this issue

**Comment by CollinsC1O** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/afk---aligned-fam-kernel).

### My background and how it can be leveraged
I'm a front-end and also a blockchain developer and I will love to work on this. please assign

**Comment by Iwueseiter** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/afk---aligned-fam-kernel).

### My background and how it can be leveraged
I'm a frontend and smart contract developer. I've contributed to Projects here on onlydust
 and with that experience, I would handle this task as expected. This would also be my first time
contributing to this project.

To implement this task, I will look at the code to identify the component. Then I will move
the componenet to the expected position as specified in the task description making sure the
styling is consistent.

### How I plan on tackling this issue
Here is how I intend to tackle this issue.

1. Ensure that the EVMProviders configuration is correct, with all required connectors such as
WalletConnect and the wagmi hooks like useConnect, useAccount, etc.

2. Confirm the correct flow for siwe-auth (Sign-In with Ethereum) to ensure user authentication is being handled securely.
Make sure siwe is properly integrated into the authentication system, especially within the 
mobile UI flow. 

3. Add WalletConnect as a connector in the EVMProviders setup.
Ensure that mobile support for WalletConnect is configured properly, especially since 
WalletConnect can be a bit more complex on mobile.

4. Fix Wrapper Issues:Ensure that EVMProviders is wrapping the correct sections of your app.
Debug any issues that occur during the addition of EVMProviders in app/Wrapper. This
include checking for proper initialization, handling async processes, or resolving any 
context issues.

5. UI Implementation:
To integrate a screen in the app for EVM wallet connection:
Add buttons or prompts that allow users to choose their wallet connection method (such as 
MetaMask or WalletConnect).
Design a seamless user flow for connecting and interacting with the wallet, ensuring the 
mobile interface is responsive and intuitive.

6. Test on Mobile:
Ensure to test the wallet connection on mobile, especially for WalletConnect, as its 
flow might differ from browser-based connections.

**Comment by NueloSE** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/afk---aligned-fam-kernel).

### My background and how it can be leveraged
i am a frontend developer

### How I plan on tackling this issue
Review EVMProviders: Check how it's set up and identify the issue in app/Wrapper.
Fix SIWE-Auth: Ensure proper authentication with Sign-In with Ethereum (SIWE), handling message signing and validation.
Fix WalletConnect: Resolve any connection problems with WalletConnect for mobile wallets.
Integrate EVM Wallet: Ensure seamless connection for MetaMask, WalletConnect, and other Ethereum wallets.
Create EVM Connect Screen: Build a user interface for connecting wallets, with status updates and error handling.
Update UI: Reflect wallet connection status in the app (show wallet address or "Connect Wallet" button).
Test: Verify wallet connections, SIWE authentication, and mobile compatibility with WalletConnect.
Cleanup: Finalize the code, improve UX, and ensure smooth functionality.

**Comment by ShantelPeters** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/afk---aligned-fam-kernel).

### My background and how it can be leveraged
HI i am Shantel a frontend and blockchain developer with vast knowledge with languages like Typescript,javascript,Cario just to name a few . i will love to work on this issue . please kindly assign i am avaliable to work 

### How I plan on tackling this issue
To approach the problem i will debug step by step to isolate specific problems

1. Check EVMProviders Setup: Ensure the EVMProviders configuration is correctly implemented.
2. siwe-auth Integration: Verify the proper integration of siwe-auth for wallet authentication.
3. WalletConnect Integration: Ensure WalletConnect is properly integrated into the app.
4. Screen EVM Connect: Implement the EVM connection screen by invoking EVMProviders and WalletConnect.
5.  Add to UI: Ensure the UI elements for EVM wallet integration are correctly placed within your app’s wrapper component.

**Comment by MSghais** [comment]
> HI @MSghais can I work on this?

Do you have an ETA for it please?

**Comment by MSghais** [comment]
> @MSghais can i work on this issue

Gm! Can you ping me on Telegram please?

**Comment by addegbenga** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/afk---aligned-fam-kernel).

### My background and how it can be leveraged
I am frontend engineer with over 5 years experience building web apps

### How I plan on tackling this issue
I will tackle this issue by:
- Going through reown docs 
- Implementing EVM connect and adding the screen on the UI.

ETA: 2days
