### ISSUE TITLE
Feed search

### ISSUE THREAD

**Issue by MSghais** [AFK-AlignedFamKernel/afk_monorepo#133]
# Description

Feed search

Feed improvment with search and filter
We can add a trending/for you directly in the top tabs.

Here is the filter in top:

![image](https://github.com/user-attachments/assets/cfeec2b3-52db-4fe9-8218-376630bbfbbf)

When you click on filter modal:

![image](https://github.com/user-attachments/assets/fab34492-c9da-4d9b-9cb9-adab5f1bc344)

**Comment by raizo07** [comment]
@MSghais can I work on this?

**Comment by martinvibes** [comment]
can i work on this

**Comment by CollinsC1O** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/afk---aligned-fam-kernel).

### My background and how it can be leveraged
Hello I'm a frontend and also a blockchain developer and I would love to work on this issue please

**Comment by martinvibes** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/afk---aligned-fam-kernel).

### My background and how it can be leveraged
Hi I would love to work on this issue

**Comment by zleypner** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/afk---aligned-fam-kernel).

### My background and how it can be leveraged
I’m a front-end developer with 3 years of experience transitioning to Web3, and I would love to make my first contribution to this project. I'm excited to take on this issue to challenge myself, learn, and contribute to the project's success.

 I'm also a member of the Dojo Coding CR community, looking forward to applying my skills in this new space while I grow and contribute to the community.

### How I plan on tackling this issue
I would implement the following solution:
I would add two distinct tabs at the top of the feed: Trending and For You. This allows me to easily navigate between the most popular posts and personalized content without leaving the feed interface.
 I would place a search bar prominently at the top of the feed so that I can quickly search for specific content, keywords, or hashtags directly within the feed.
Next to the search bar, I would include a filter icon or button that, when tapped, opens up various filtering options like date range, content type, popularity, location, or followed accounts.
I would make the filter/search bar sticky, ensuring it remains accessible at the top of the screen as I scroll through the feed.
I would also include a dropdown menu or buttons to filter content by specific categories or tags, allowing me to refine my search and view posts that match my interests more closely.
If I run into any problems or questions, I’ll reach out to the maintainers for assistance.

**Comment by Benjtalkshow** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/afk---aligned-fam-kernel).

### My background and how it can be leveraged
As a full-stack developer, I have a lot of experience working with frontend technologies like TypeScript, React, and Next.js. I've already contributed to this project by implementing features like the Nostr bookmark hook and the useRepost hook, which helped me understand how the project is set up and how everything connects. With this background, I feel confident in making these new improvements to the feed.

### How I plan on tackling this issue
First, I’ll review how the feed currently works so that I can integrate the new search functionality without causing any issues. I’ll then add a search bar at the top of the feed where users can type keywords to find specific posts. When a user searches, the system will fetch and show posts that match their input.

Next, I’ll add filters. These will let users sort through the content by things like "recent posts" or "popular posts." The filters will be placed at the top of the feed, either as dropdowns or buttons for easy access.

To make the feed more personalized, I’ll introduce two tabs: "Trending" and "For You." The "Trending" tab will show popular posts, while the "For You" tab will display posts that are more personalized based on the user’s activity on the platform. I'll ensure these tabs are easy to find and use.

On the backend, I'll ensure that the search and filtering features are optimized for speed and that the system fetches personalized content efficiently without slowing down the feed.

After development, I’ll test everything to make sure it works smoothly, even in cases where there are no search results or if the system is under heavy load. I’ll also get feedback from the team to make improvements where needed, ensuring the feed is simple and enjoyable to use.

**Comment by Ayoazeez26** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/afk---aligned-fam-kernel).

### My background and how it can be leveraged
Hi

### How I plan on tackling this issue
Implement search filter 
ETA - 48hours to completion
