### ISSUE TITLE
Swap, Mint & Withdraw UI

### ISSUE THREAD

**Issue by MSghais** [AFK-AlignedFamKernel/afk_monorepo#33]
Create screen and components Swap token to our token.

We can create a modular component because this component can be used on different screens:

Can we use it to mint for Aligned tokens: BTC, EVM, USD.

We can mint few tokens depending on the Input token and blockchain network:

- [] Picker tokens enabled
- [] Input amount
-[] Output address
- [] Output amount ( send a callback function into the component

aBTC, aUSD, aETH. 
We can only mint with a wrapper coin similar to the

Token in Starknet:
- wBTC.
- Dai, USDT, USDC

Token in EVM:
- wBTC, tBTC, cbBTC.
-Dai & USDC

**Comment by Gift-Naomi** [comment]
Hi

**Comment by ooochoche** [comment]
Hi

**Comment by petersdt** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/afk---aligned-fam-kernel).

### My background and how it can be leveraged
hi

**Comment by NueloSE** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/afk---aligned-fam-kernel).

### My background and how it can be leveraged
i am a frontend deve

### How I plan on tackling this issue
i would like to handle this task

**Comment by BlackStarkGoku** [comment]
Hello @MSghais, as I discussed with you, I would like to contribute!

**Comment by Supa-mega** [comment]
hi @MSghais having previously gathered prior knowledge with my experience and expertise i will love to be assign this task ,loking foward to your responce

**Comment by BlackStarkGoku** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/afk---aligned-fam-kernel).

### My background and how it can be leveraged
I am a Full-Stack Software Engineer (React/Typescript/Cairo) contributing to Starknet Eco-system.

### How I plan on tackling this issue
I will understand by discussing with the project lead the scope of mission, implement a component to resolve the issue

**Comment by sajalbnl** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/afk---aligned-fam-kernel).

### My background and how it can be leveraged
I have 2 years of experience as a front-end developer, with expertise in JavaScript, React.js, CSS, and HTML. I've built full-stack projects like Crypto Bank, handling both front-end and back-end development. My skills in creating responsive, dynamic interfaces make me well-equipped to contribute effectively to your project.

**Comment by PoulavBhowmick03** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/afk---aligned-fam-kernel).

### My background and how it can be leveraged
I'm Poulav Bhowmick, a software engineer at Invisible Studios with a robust background in TypeScript, Rust, Solidity Cairo, fullstack development and blockchain technology. My experience includes building robust applications, optimizing functionalities and blockchain integration. I have actively participated in events and open source contributions, enhancing my capability to tackle real-world tech challenges. My projects can be viewed on my GitHub Profile and OnlyDust Profile. Plus I´m active member of Starknet community🇷.

### How I plan on tackling this issue
We need to build a modular component for swapping tokens, which can also be used to mint aligned tokens (e.g., aBTC, aUSD, aETH) depending on the input token and blockchain network (StarkNet, EVM). The component should be flexible enough to be used on different screens.

**Component Features:**

1. Token Picker:
   - Allow users to select from a list of tokens available on the network.
   - Should support tokens across multiple blockchains (StarkNet, EVM).
   - Enable/disable tokens based on network compatibility.

2. Input Amount:
   - Users will input the amount of the token they wish to swap/mint.
   - Should validate input based on the selected token’s precision and balance.

3. Output Address:
   - Field to input the recipient address where the output token will be sent.
   - Include validation to ensure the address is correct for the selected blockchain network.

4. Output Amount (Callback Function):
   - Calculate the output amount based on the input amount, selected token, and current exchange/minting rate.
   - This should be modular, allowing the component to accept a callback function to compute the output amount dynamically based on external factors (e.g., API rates, blockchain state).

5. Token Wrapper Support:
   - Only allow minting with wrapper tokens like wBTC on StarkNet and tBTC, cbBTC on EVM.
   - Ensure the component handles the logic for different wrapper tokens automatically.

Implementation Notes:
- **Modularity:** The component should be built with reusability in mind, allowing it to be easily integrated into different parts of the app.
- **Network-Specific Logic:** Depending on the selected token, the component should automatically adjust to the corresponding blockchain logic (StarkNet or EVM).
- **Validation:** Implement thorough validation for input fields, especially for blockchain addresses and amounts.
- **Extensibility:** Design the component so that it can be extended to support additional networks and tokens in the future.

**Example Use Cases:**
- Swap aBTC to ETH on StarkNet.
- Mint aUSD by swapping wBTC on EVM.

This approach ensures that the component remains flexible, reusable, and easy to maintain as the project grows.

**Comment by MSghais** [comment]
Thank you everyone for applying!

As we said, we prioritize a clear ETA (Estimated Time of Arrival) for the features in priorities like this one, with descriptions of the tasks, etc.
