### ISSUE TITLE
Indexer Apibara of Launchpad

### ISSUE THREAD

**Issue by MSghais** [AFK-AlignedFamKernel/afk_monorepo#40]
Fix indexer in the apps/indexer.
Improve backend routes in the apps/data-backend.
Needed for #44 

- Test all events with apibara indexer.
- Modify the init Postgres if needed.

- Change the events of the contracts if needed: Launchpad
- Fix and finish indexer scripts:
buy-coin.js
pump-coin.js
deploy-coin.js

**Comment by EjembiEmmanuel** [comment]
@

**Comment by Ugo-X** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/afk---aligned-fam-kernel).

### My background and how it can be leveraged
I am a Full Stack blockchain Developer with expertise in Next.js, Nest.js, TypeScript, JavaScript, React, Node.js, Three.js, and Solidity. My journey with OnlyDust hackathons began at Edition 1, and I've since made 47 contributions across 11 projects. With my extensive experience on the OnlyDust platform (profile:  https://app.onlydust.com/u/Ugo-X), I've honed my skills in delivering quality solutions under pressure.
I bring a unique blend of technical proficiency and user-focused design to every project, whether it's crafting immersive 3D experiences or developing smart contracts. My track record shows I can adapt quickly and contribute effectively to diverse challenges.
As we surf through Edition 7, I'm excited to leverage my skills and hackathon experience to push the boundaries of blockchain development. I'm confident in my ability to tackle new challenges and drive innovation in this space.


### How I plan on tackling this issue
Understood, I will approach this issue in the following steps:

1. **Analyze the Current Indexer Implementation**:
   - Examine the existing code in the `apps/indexer` directory to understand the current implementation.
   - Identify any issues or areas for improvement in the indexer functionality.
   - Review the integration between the indexer and the backend routes in the `apps/data-backend` directory.

2. **Test All Events with the Apibara Indexer**:
   - Set up a comprehensive test suite to verify the indexer's handling of all relevant events.
   - Use the Apibara indexer to index the events and ensure the data is being correctly processed and stored.
   - Identify any issues or edge cases in the event handling and indexing process.

3. **Modify the Postgres Initialization (if needed)**:
   - Assess the current Postgres setup and schema used by the indexer and backend.
   - Determine if any changes or modifications are required to the Postgres initialization process to accommodate the indexer's needs.
   - Implement the necessary changes to the Postgres setup, ensuring a smooth integration with the indexer and backend.

4. **Update the Events of the Launchpad Contracts (if needed)**:
   - Review the event definitions and handling in the Launchpad contracts.
   - Identify any changes or improvements that may be required to the contract events to better support the indexer's functionality.
   - Implement the necessary modifications to the contract events, ensuring backward compatibility and smooth transition.

5. **Fix the Routes in the Data Backend**:
   - Examine the existing routes in the `apps/data-backend` directory, focusing on their integration with the indexer.
   - Identify any issues or areas for improvement in the backend routes, such as performance, error handling, or data consistency.
   - Refactor and fix the problematic routes to ensure seamless integration between the indexer and the backend.

6. **Testing and Validation**:
   - Implement comprehensive unit tests to verify the correct behavior of the indexer and the backend routes.
   - Perform end-to-end testing to ensure the indexer and backend work together as expected, handling events and serving data correctly.
   - Validate the overall system's functionality, performance, and reliability under various scenarios.

7. **Documentation and Knowledge Sharing**:
   - Document the changes made to the indexer and backend, including any modifications to the Postgres setup or contract events.
   - Provide clear instructions on how to set up, configure, and maintain the updated indexer and backend components.
   - Share the knowledge and insights gained during the development process with the wider team to facilitate future maintenance and improvements.

By following this approach, I will thoroughly address the issues in the indexer and backend, ensuring the reliable and efficient processing of events and the seamless integration between the different components of the system. The focus will be on improving the overall stability, performance, and maintainability of the indexer and backend components.

**Comment by MatiasAchucarro** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/afk---aligned-fam-kernel).

### My background and how it can be leveraged
I am a passionate and results-driven web developer, currently deepening my knowledge in web3 technologies, Cairo, and open-source development through Dojo Coding. My skill set includes expertise in JavaScript, React, HTML, CSS, C# with .NET Entity Framework, and more. I also have experience with tools like Git, GitHub, SQL Server, and Postman. My focus has been on building solid web applications, from task lists to full-fledged CRUD systems, with front-end, back-end, and database integration.

This will be my first contribution to the open-source ecosystem, and I am excited to learn and collaborate on innovative projects, particularly those involving Cairo.

### How I plan on tackling this issue
to tackle this problem, I’d first review the indexer in apps/indexer and identify any issues. I’d then improve the backend routes in apps/data-backend for better organization and functionality. I’d test all events with the Apibara indexer to ensure correct behavior. If needed, I’d adjust the Postgres initialization and modify the contract events in Launchpad. Lastly, I’d verify and fix any backend routes related to the indexer to ensure smooth integration and functionality across the app.

**Comment by fishonamos** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/afk---aligned-fam-kernel).

### My background and how it can be leveraged
I have worked on something similar recently. 


### How I plan on tackling this issue
I will fix indexer indexer and optimize the backend routes.
Next, I will test the events with the Apibara test framework

Ref: https://github.com/fishonamos/strkindex/tree/apiv2

**Comment by MSghais** [comment]
> I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/afk---aligned-fam-kernel).
> ### My background and how it can be leveraged
> 
> I have worked on something similar recently.
> ### How I plan on tackling this issue
> 
> I will fix indexer indexer and optimize the backend routes. Next, I will test the events with the Apibara test framework
> 
> Ref: https://github.com/fishonamos/strkindex/tree/apiv2

Gm! Do you have an ETA please?

The indexer is the main part please, doing other issue for the backend

**Comment by MSghais** [comment]
> I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/afk---aligned-fam-kernel).
> ### My background and how it can be leveraged
> 
> I am a Full Stack blockchain Developer with expertise in Next.js, Nest.js, TypeScript, JavaScript, React, Node.js, Three.js, and Solidity. My journey with OnlyDust hackathons began at Edition 1, and I've since made 47 contributions across 11 projects. With my extensive experience on the OnlyDust platform (profile: https://app.onlydust.com/u/Ugo-X), I've honed my skills in delivering quality solutions under pressure. I bring a unique blend of technical proficiency and user-focused design to every project, whether it's crafting immersive 3D experiences or developing smart contracts. My track record shows I can adapt quickly and contribute effectively to diverse challenges. As we surf through Edition 7, I'm excited to leverage my skills and hackathon experience to push the boundaries of blockchain development. I'm confident in my ability to tackle new challenges and drive innovation in this space.
> ### How I plan on tackling this issue
> 
> Understood, I will approach this issue in the following steps:
> 
>     1. **Analyze the Current Indexer Implementation**:
>        
>        * Examine the existing code in the `apps/indexer` directory to understand the current implementation.
>        * Identify any issues or areas for improvement in the indexer functionality.
>        * Review the integration between the indexer and the backend routes in the `apps/data-backend` directory.
> 
>     2. **Test All Events with the Apibara Indexer**:
>        
>        * Set up a comprehensive test suite to verify the indexer's handling of all relevant events.
>        * Use the Apibara indexer to index the events and ensure the data is being correctly processed and stored.
>        * Identify any issues or edge cases in the event handling and indexing process.
> 
>     3. **Modify the Postgres Initialization (if needed)**:
>        
>        * Assess the current Postgres setup and schema used by the indexer and backend.
>        * Determine if any changes or modifications are required to the Postgres initialization process to accommodate the indexer's needs.
>        * Implement the necessary changes to the Postgres setup, ensuring a smooth integration with the indexer and backend.
> 
>     4. **Update the Events of the Launchpad Contracts (if needed)**:
>        
>        * Review the event definitions and handling in the Launchpad contracts.
>        * Identify any changes or improvements that may be required to the contract events to better support the indexer's functionality.
>        * Implement the necessary modifications to the contract events, ensuring backward compatibility and smooth transition.
> 
>     5. **Fix the Routes in the Data Backend**:
>        
>        * Examine the existing routes in the `apps/data-backend` directory, focusing on their integration with the indexer.
>        * Identify any issues or areas for improvement in the backend routes, such as performance, error handling, or data consistency.
>        * Refactor and fix the problematic routes to ensure seamless integration between the indexer and the backend.
> 
>     6. **Testing and Validation**:
>        
>        * Implement comprehensive unit tests to verify the correct behavior of the indexer and the backend routes.
>        * Perform end-to-end testing to ensure the indexer and backend work together as expected, handling events and serving data correctly.
>        * Validate the overall system's functionality, performance, and reliability under various scenarios.
> 
>     7. **Documentation and Knowledge Sharing**:
>        
>        * Document the changes made to the indexer and backend, including any modifications to the Postgres setup or contract events.
>        * Provide clear instructions on how to set up, configure, and maintain the updated indexer and backend components.
>        * Share the knowledge and insights gained during the development process with the wider team to facilitate future maintenance and improvements.
> 
> 
> By following this approach, I will thoroughly address the issues in the indexer and backend, ensuring the reliable and efficient processing of events and the seamless integration between the different components of the system. The focus will be on improving the overall stability, performance, and maintainability of the indexer and backend components.

Do you have an ETA please?

**Comment by fishonamos** [comment]
> > I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/afk---aligned-fam-kernel).
> > ### My background and how it can be leveraged
> > I have worked on something similar recently.
> > ### How I plan on tackling this issue
> > I will fix indexer indexer and optimize the backend routes. Next, I will test the events with the Apibara test framework
> > Ref: https://github.com/fishonamos/strkindex/tree/apiv2
> 
> Gm! Do you have an ETA please?
> 
> The indexer is the main part please, doing other issue for the backend

ETA: Maximum: 1 - 2 days from now. Ready tommorow.

**Comment by fishonamos** [comment]
Is it a blocking issue? @MSghais

**Comment by MSghais** [comment]
> Is it a blocking issue? @MSghais

No, let's discuss it please! 
Can you ping me also on Telegram: MSG_Encrypted. Also please join the AFK group

**Comment by fishonamos** [comment]
> AFK

Ok. Replied you on TG. @FishonAmos

**Comment by fishonamos** [comment]
> > Is it a blocking issue? @MSghais
> 
> No, let's discuss it please! Can you ping me also on Telegram: MSG_Encrypted. Also please join the AFK group

Ok. Replied you on TG: FishonAmos
