### ISSUE TITLE
Backend Routes indexer

### ISSUE THREAD

**Issue by MSghais** [AFK-AlignedFamKernel/afk_monorepo#44]
Depends on #40 to be finished.

New endpoints:

- Stats: last price, liquidity_raised
- My share: amount holded, amount buy and sell by me
- Holders and tokens distributions endpoints.
- Graph: get candle based on tx sell and buy and send it as a candle form

Ideas welcomed

Improve backend routes in the apps/data-backend.

- Fix routes in the apps/data-backend for the indexer:
deploy-launch
deploy-coin
buy-coin
sell-coin

- Create a Prisma model for Launchpad statistics: LaunchStats, Holders stats etc.
- Model for Stats sum (sum for a launch, sum amount invested, all holders, etc)

**Comment by mitarumi** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/afk---aligned-fam-kernel).

### My background and how it can be leveraged
I am a web3 developer with experience in various languages

**Comment by kateberryd** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/afk---aligned-fam-kernel).

### My background and how it can be leveraged
I would love to work on this

**Comment by GoSTEAN** [comment]
@MSghais can I be assigned

**Comment by ScottyDavies** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/afk---aligned-fam-kernel).

### My background and how it can be leveraged
I am front end developer with years of experience.
this will be my first time contributing to the ecosystem and i am ready to work

### How I plan on tackling this issue
I would approach this issue with following steps

Understanding the Existing Codebase:
First, I would review the existing codebase, particularly the apps/data-backend folder, to understand the current structure and implementation of the routes.
I would also familiarize myself with the overall application architecture and the way the frontend interacts with the backend.
Reviewing the Existing Routes:
I would closely examine the existing routes (deploy-launch, deploy-coin, buy-coin, sell-coin) and understand their purpose, the data they handle, and how they are currently implemented.
I would identify any issues, such as redundancy, lack of consistency, or inefficient handling of data.
Proposing Route Improvements:
Based on the understanding gained in the previous steps, I would propose improvements to the existing routes. This might include:
Streamlining the route structure and naming conventions
Optimizing the data handling and response formats
Enhancing error handling and providing more informative error messages
Improving the overall consistency and maintainability of the routes
Designing the Prisma Model:
I would work closely with the backend team to design the Prisma model for the Launchpad statistics, including the LaunchStats and HoldersStats entities.
I would ensure that the model captures all the necessary data points, such as total amount invested, number of holders, and any other relevant statistics.
I would also consider the potential use cases and queries that the frontend might need to perform on this data, and design the model accordingly.
Implementing the Changes:
I would collaborate with the backend team to implement the proposed route improvements and the new Prisma model.
This would involve modifying the existing routes, adding new routes (if necessary), and implementing the Prisma model and its associated database migrations.
Throughout the implementation, I would ensure that the changes are aligned with the overall application architecture and best practices.
Testing and Integration:
After the changes have been implemented, I would work with the backend team to thoroughly test the new routes and the Prisma model.
I would ensure that the frontend can seamlessly interact with the improved backend routes and that the data provided by the Launchpad statistics model is accurate and reliable.
I would also test the integration between the frontend and the backend, verifying that the data flow and user experience are not disrupted.
Documentation and Knowledge Sharing:
I would document the changes made to the routes and the new Prisma model, including the rationale behind the decisions and any relevant best practices.
I would share this documentation with the rest of the development team to ensure that everyone understands the improvements and can maintain the codebase going forward.

**Comment by ShantelPeters** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/afk---aligned-fam-kernel).

### My background and how it can be leveraged
With my experience in frontend development and understanding of backend integration, I can efficiently improve and fix backend routes and create Prisma models for Launchpad statistics and other required metrics.

### How I plan on tackling this issue
1. **Complete Dependencies**: Ensure #40 is finished before starting.
2. **Fix Routes**: Update and debug backend routes for `deploy-launch`, `deploy-coin`, `buy-coin`, and `sell-coin`.
3. **Create Prisma Models**: Define models for `LaunchStats`, `HoldersStats`, and aggregated stats.
4. **Test and Verify**: Ensure routes and models function correctly with thorough testing.

**Comment by renzobanegass** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/afk---aligned-fam-kernel).

### My background and how it can be leveraged
Hey, I'm Renzo, a Software Engineer with over 5 years of experience in the industry, and also a member of Dojo Coding, I have worked for plenty of projects as Backend Developer like Trivia Crack and Stumble Guys, I started my journey in Web3 last month and would love to help you with this issue to keep learning and maybe dedicate myself full time to Web3 Development.

### How I plan on tackling this issue
To tackle the Backend Routes indexer issue, I would proceed with the following steps:

Review Issue #40:

Since this task depends on #40 being completed, I will first review the status of that issue to ensure all prerequisites are in place.
Examine Current Backend Routes:

I will analyze the current implementation of the routes in the apps/data-backend to understand the existing structure and functionality.
Specifically, I will focus on the deploy-launch, deploy-coin, buy-coin, and sell-coin routes to identify any areas for improvement or necessary adjustments.
Prisma Model Creation:

I will create a new Prisma model for Launchpad statistics, including entities such as LaunchStats and HoldersStats.
I will also define a model to handle cumulative statistics (StatsSum), ensuring it captures relevant data like the total sum for a launch, total amount invested, and all holders.
Refactor and Implement Backend Routes:

With the Prisma models in place, I will refactor the existing routes to incorporate these models.
This will involve adjusting the logic in deploy-launch, deploy-coin, buy-coin, and sell-coin to utilize the new statistics data appropriately.
Testing and Validation:

I will write and run tests to ensure the new models and refactored routes work correctly, covering various scenarios and edge cases.
This will also include validating that the data aggregation for stats is accurate and the routes handle all necessary operations smoothly.
Documentation:

Finally, I will update any relevant documentation to reflect the changes in the routes and the addition of the new Prisma models.
Submit a Pull Request:

Once everything is in order, I will submit a PR for review, providing a detailed explanation of the changes, along with test results and any relevant documentation updates.

**Comment by diegoTech14** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/afk---aligned-fam-kernel).

### My background and how it can be leveraged
Hello @MSghais I'm Diego Duarte Fernández from Costa Rica and Dojo Coding member this is my OnlyDust profile: https://app.onlydust.com/u/diegoTech14, I would love to help with this issue. 

I have experience with Nodejs, Prisma and modeling databases. I can efficiently optimize routes and design data models. I would love to ensure the correct functionality of the routes!

### How I plan on tackling this issue
1. Understanding the dependencies: 
* I will ensure any necessary changes or dependencies are addressed before moving forward.

2. Analyzing the implementation: 
* I will analyze the current routes implementation to understand the structure and getting context to focus on `deploy-launch`, `deploy-coin`, `buy-coin`,`sell-coin` routes.

3. Design Prisma Models: 
* Create the correctly Prisma models for `LaunchStats` and `HoldersStats`, ensuring they are efficient and aligned with the application’s needs.

4. Stats models: 
* Focusing on summing launch investments and holder data for quick and efficient queries I will create the respective model.

5. Testing: 
* I will test the routes applying any necessary adjustment to ensure the correct functionality

Thanks for the consideration.

Best regards, 

Diego Duarte Fernández

**Comment by JorgeOehrens** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/afk---aligned-fam-kernel).

### My background and how it can be leveraged
I have a strong background in backend development, particularly in building and optimizing APIs with Node.js and Express. I have hands-on experience using Prisma for database management, including designing complex data models that cater to various application needs. My expertise also extends to integrating and refining routes for different backend functionalities, ensuring efficient and secure data handling. This experience aligns well with the requirements of this project, as I can leverage my skills to improve and fix backend routes, create robust Prisma models, and implement effective solutions for handling statistics.


### How I plan on tackling this issue
To approach this problem, I would first review the existing routes in apps/data-backend, focusing on identifying and resolving any issues in the deploy-launch, deploy-coin, buy-coin, and sell-coin routes. I would then design and implement Prisma models for LaunchStats and other statistical data, ensuring they capture all relevant metrics like total investments and holder statistics. Lastly, I’d refactor and optimize the code to ensure that it scales efficiently, aligning with the broader goals of the application and providing accurate, real-time data for users.

**Comment by fishonamos** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/afk---aligned-fam-kernel).

### My background and how it can be leveraged
Backend Developer.

### How I plan on tackling this issue
I will refactor the backend logic according to the events tracked by the indexer. I will also update the resolvers, GraphQL schema, and any other parts of the backend service to ensure everything works correctly. Kindly assign.

**Comment by MSghais** [comment]
> I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/afk---aligned-fam-kernel).
> 
> ### My background and how it can be leveraged
> I'm backend developer I have experience with express and prisma
> 
> ### How I plan on tackling this issue
> I would refactor this current implementation to suite the changes made to the indexer. I can get this done in 2 business days after the issue it's depending on is completed

Gm @kateberryd! Can you ping me on Telegram please, I can find other issue for you with pleasure!

I think I'm gonna assign the person that's have work on the indexer things to done it fast, and bring your others issues for you

**Comment by moteeullahazmi** [comment]
can i try this?
