### ISSUE TITLE
Finish hooks private group integration

### ISSUE THREAD

**Issue by MSghais** [AFK-AlignedFamKernel/afk_monorepo#67]
Finish the integration of the hook private group in the UI.

**Comment by EjembiEmmanuel** [comment]
@MSghais I'd love to work on this

**Comment by addegbenga** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/afk---aligned-fam-kernel).

### My background and how it can be leveraged
A frontend engineer with over 5 years experience in software development

### How I plan on tackling this issue
To tackle this issue:
-I will integrate all the available group hooks on the UI.
-Test and make sure everything works correctly.

**Comment by lindsaymoralesb** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/afk---aligned-fam-kernel).

### My background and how it can be leveraged
Software Engineer based in Costa Rica. I'm part of Dojo Coding and thanks to that I've already successfully contributed to 4 ODHacks in various projects, feel free to check my profile and contributions.
I've been working over the past 4.5 years as a full stack developer, specializing myself in frontend development.

### How I plan on tackling this issue
I recently contributed to the UI development of private messages on this project, so I have a good understanding of all the code. I'll take a similar approach to that issue I already had to solve since these two are kind of similar.
I'll take a look at the already developed hooks and integrate them into the private group screen based on how hooks are already being used in other parts of the platform.

**Comment by MSghais** [comment]
@EjembiEmmanuel @lindsaymoralesb gonna add more issues asap in DM you.

@addegbenga let me assign it to you because you did the hook and ui, let's finish the integration fastly.
